const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
require.extensions['.ts'] = (module, filename) => module._compile(ts.transpileModule(fs.readFileSync(filename, 'utf8'), {
  compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true },
}).outputText, filename);
const { HorseRiding: WorkerRiding } = require('../../../worker/horseRiding.ts');
const { HorseRiding: ClientRiding } = require('../../../features/village/horseRiding.ts');
const { VillageMovement } = require('../../../features/village/movement.ts');
const { setAuthoredWorld } = require('../../../features/village/environment.ts');
setAuthoredWorld({ terrain: { base: 'flat', samples: [] }, openWorld: true, paths: [], items: [], bridges: [], walkable: [] });
const horse = { state: { id: 'test-horse', kind: 'horse', owner: 'rider', mode: 'ride', x: 12, y: 0, z: 20, heading: 0, speed: 0 }, movement: new VillageMovement([], () => {}) };
const worker = new WorkerRiding();
const forward = { forward: 1, turn: 0, sprint: false, brake: false, sequence: 1 };
assert(worker.input(horse, forward, 1000));
assert(worker.input(horse, { ...forward, turn: 1, sequence: 2 }, 1016), 'A steering change one frame after forward must be accepted');
assert(worker.input(horse, { ...forward, turn: -1, sequence: 3 }, 1032), 'Rapid reverse steering must replace the held turn');
assert(!worker.input(horse, { ...forward, sequence: 2 }, 1048), 'Old sequenced packets cannot replace newer steering');
assert(!worker.input(horse, { ...forward, turn: NaN, sequence: 4 }, 1050));
assert(!worker.input(horse, { ...forward, sequence: 1.5 }, 1050));
worker.step(horse, 1, .016, 1048, () => false);
assert(horse.state.heading < 0, 'The next Worker step uses the most recent steering');

const sent = [], client = new ClientRiding();
client.connect(input => sent.push(input));
const accepted = { ...horse.state, x: 12, z: 20, heading: 0, speed: 0, ride: { velocity: 0, input: null, at: 1000, sequence: 0, blocked: false } };
client.sync([accepted], 'rider', 1000, 0);
client.update(new Set(['w', 'a']), true, 0);
const pose = client.sample(.016, 1, horse.movement, () => false, 16);
assert(pose.heading > .02, 'The accepted rider sees steering in the next frame, before any reply');
assert.equal(accepted.heading, 0, 'Visual prediction must never mutate the accepted shared actor');
assert.equal(sent.length, 1);
const initialHeading = pose.heading;
client.update(new Set(['w', 'd']), true, .016);
const reversed = client.sample(.016, 1, horse.movement, () => false, 32);
assert(reversed.heading < initialHeading, 'Rapid changes affect the next local frame too');
const reconciled = { ...accepted, heading: -.1, ride: { velocity: 0, input: sent.at(-1), at: 1016, sequence: sent.at(-1).sequence, blocked: false } };
client.sync([reconciled], 'rider', 1048, 80);
assert(client.sample(.016, 1, horse.movement, () => false, 96).heading < initialHeading, 'Snapshots reconcile to accepted steering');
client.sync([{ ...reconciled, ride: { ...reconciled.ride, blocked: true } }], 'rider', 1080, 112);
assert.equal(client.sample(.016, 1, horse.movement, () => false, 128).heading, -.1, 'Race countdown cannot predict motion');
client.sync([reconciled], 'rider', 1120, 144);
const stale = client.sample(.016, 1, horse.movement, () => false, 800);
assert.equal(stale.heading, reconciled.heading, 'Delivery stalls stop prediction at the accepted pose');
client.sync([{ ...accepted, owner: 'other' }], 'rider', 1120, 816);
assert.equal(client.sample(.016, 1, horse.movement, () => false, 832), null, 'Losing ownership clears predicted motion');
client.clear();
const touch = new ClientRiding(); touch.connect(() => {});
touch.sync([accepted], 'rider', 1000, 0);
touch.update(new Set(), true, 0, { forward: .5, turn: -.6, sprint: false, brake: false });
const touchHeading = touch.sample(.016, 1, horse.movement, () => false, 16).heading;
assert(touchHeading < -.01, 'Analog touch steering responds before a reply');
touch.update(new Set(), true, .016, { forward: .5, turn: -.6, sprint: false, brake: true });
assert(Math.abs(touch.sample(.016, 1, horse.movement, () => false, 32).heading - touchHeading) < 1e-10,
  'Brake keeps the visual heading fixed');

const collision = new ClientRiding(); collision.connect(() => {});
collision.setColliders([{ x: 12, z: 22, w: 4, d: .2 }, { x: 150, z: 150, w: 1, d: 1 }]);
collision.sync([{ ...accepted, ride: { ...accepted.ride, velocity: 9, input: { ...forward, sprint: true } } }], 'rider', 1000, 0);
const solid = collision.sample(.016, 1, horse.movement, () => false, 350);
assert(solid.z < 21.1, 'The nearby collision probe stops the full footprint at a solid');
const occupants = new ClientRiding(); occupants.connect(() => {});
occupants.sync([{ ...accepted, ride: { ...accepted.ride, velocity: 9, input: { ...forward, sprint: true } } }], 'rider', 1000, 0);
assert.equal(occupants.sample(.016, 1, horse.movement, () => true, 350).z, accepted.z, 'Occupied shared ground cannot advance visually');
const bounded = new ClientRiding(); bounded.connect(() => {});
bounded.sync([{ ...accepted, ride: { ...accepted.ride, velocity: 9, input: { ...forward, sprint: true } } }], 'rider', 1000, 0);
const limit = bounded.sample(.016, 1, horse.movement, () => false, 350).z;
assert(limit <= accepted.z + 9 * .35 + 1e-8, 'Visual motion stays within the 350ms projection horizon');
assert.equal(bounded.sample(.016, 1, horse.movement, () => false, 390).z, limit, 'A stalled stream cannot advance beyond the horizon');
const legacy = new ClientRiding(); legacy.connect(() => {});
const { ride: _ride, ...oldActor } = accepted;
legacy.sync([oldActor], 'rider', 1000, 0);
assert.equal(legacy.sample(.016, 1, horse.movement, () => false, 16), null, 'Older Workers retain accepted-path rendering');
assert.equal(worker.snapshot(horse, 2000, false).input, null, 'Expired accepted input is not replayed from snapshots');
worker.stop(horse);
assert.equal(worker.snapshot(horse, 2000, false).sequence, 0, 'Releasing a ride clears its acknowledgement and velocity');
console.log('Horse rapid-input, next-frame keyboard/touch response, reconciliation, countdown, collision, stall and ownership checks pass.');
