const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
(async()=>{const b=await chromium.launch({headless:true,channel:'chrome'});const output=process.env.OUTPUT_DIR||'/tmp/cosy-birds';fs.mkdirSync(output,{recursive:true});const checks=[],errors=[],placed={},check=(ok,label)=>{if(!ok)throw Error(label);checks.push(label);};const baseline=path.join(__dirname,'../presets/current-village.json'),hash=()=>crypto.createHash('sha256').update(fs.readFileSync(baseline)).digest('hex'),before=hash();
try{const p=await b.newPage({viewport:{width:1440,height:900}});p.on('pageerror',e=>errors.push(String(e)));await p.goto(process.env.EDITOR_URL||'http://127.0.0.1:3047/');await p.waitForFunction(()=>window.cosyStudio,{timeout:60000});
const wanted=[['white-dove','White dove'],['wren-caretaker','Wren · bird caretaker'],['bird-clearing-terrace','Bird clearing terrace'],['bird-feeding-dish','Sourdough feeding dish'],['bird-clearing-bench','Birdwatching bench'],['bird-clearing-flowers','Dove clearing flower border'],['path-5','Bird clearing approach']];
for(const[id,name]of wanted){await p.getByRole('searchbox').fill(name);const card=p.locator(`[data-asset="${id}"]`);await card.waitFor();await p.waitForFunction(id=>document.querySelector(`[data-asset="${id}"] img`)?.getAttribute('src')?.startsWith('data:image'),id,{timeout:60000});check(true,name+' has a library preview');await card.click();const bounds=await p.locator('#viewport').boundingBox();await p.mouse.click(bounds.x+bounds.width*.52,bounds.y+bounds.height*.55);await p.waitForFunction(id=>cosyStudio.snapshot().layout.objects.some(o=>o.id===cosyStudio.selection()[0]&&o.asset===id),id);
const changes={'position-0':'-24','position-1':id==='white-dove'?'1':'0','position-2':'-31','rotation-1':'35','scale-0':'1.2'};for(const[field,value]of Object.entries(changes)){await p.locator('#'+field).fill(value);await p.locator('#'+field).press('Tab');}
const item=await p.evaluate(()=>{const s=cosyStudio.snapshot();return s.layout.objects.find(o=>o.id===cosyStudio.selection()[0]);});check(item.asset===id&&item.position[0]===-24&&item.position[2]===-31&&item.rotation[1]===35&&item.scale.every(n=>Math.abs(n-1.2)<.001),name+' supports selection, placement, rotation and scale');
placed[id]=item.id;
if(id==='white-dove'){await p.locator('#focus-object').click();await p.waitForTimeout(300);await p.screenshot({path:path.join(output,'editor-dove.png')});await p.locator('#home-view').click();}}
await p.getByLabel('Layout name',{exact:true}).fill('Bird asset QA working copy');await p.getByLabel('Layout name',{exact:true}).press('Tab');await p.locator('#save').click();await p.waitForFunction(()=>cosyStudio.snapshot().fileId);const snap=await p.evaluate(()=>cosyStudio.snapshot());const response=await p.request.get((process.env.EDITOR_URL||'http://127.0.0.1:3047')+'/api/layouts/'+snap.fileId);const saved=(await response.json()).layout;
for(const[id,name]of wanted){const item=saved.objects.find(o=>o.id===placed[id]);check(item&&item.rotation[1]===35&&item.scale[0]===1.2,name+' transform survives file save');}
await p.reload();await p.waitForFunction(()=>window.cosyStudio,{timeout:60000});const reloaded=await p.evaluate(()=>cosyStudio.snapshot());check(JSON.stringify(reloaded.layout)===JSON.stringify(saved),'Working-copy transforms survive a browser reload');check(hash()===before,'Preserved default layout stays byte-identical');check(!errors.length,'No editor application errors');fs.writeFileSync(path.join(output,'editor-checks.json'),JSON.stringify({checks,errors,baselineSha256:before,savedLayout:snap.fileId},null,2));console.log(checks.length+' bird editor checks passed');}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
