// PLAYWRIGHT_PATH=/path/to/playwright STUDIO_URL=http://127.0.0.1:3041 node tools/village-editor/tests/browser.cjs
// Use the server's --layouts-dir with a temporary directory to keep QA files out of real designs.
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const url = process.env.STUDIO_URL || 'http://127.0.0.1:3041';
const evidence = process.env.STUDIO_EVIDENCE || '/tmp/cosy-studio-evidence';
fs.mkdirSync(evidence, {recursive:true});
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const checks=[], errors=[]; const check=(v,name)=>{assert(v,name);checks.push(name);console.log('PASS',name)};
 try {
  const context=await browser.newContext({viewport:{width:1600,height:1000},acceptDownloads:true});
  const page=await context.newPage();
  page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
  await page.goto(url);await page.waitForFunction(()=>!!window.cosyStudio,{timeout:60000});
  await page.waitForFunction(()=>document.querySelectorAll('.asset-card img[src]').length===document.querySelectorAll('.asset-card').length);
  const snapshot=()=>page.evaluate(()=>window.cosyStudio.snapshot());
  const presetBefore=await (await page.request.get(url+'/api/presets/current-village')).json();
  const playableBefore=await (await page.request.get(url+'/api/playable')).json();
  const original=presetBefore.layout;
  let state=await snapshot();check(state.fileId===null&&state.layout.name==='My village','Opens an independent working copy');
  check(JSON.stringify(state.layout.objects)===JSON.stringify(playableBefore.layout.objects),'Working copy starts from the playable world');
  await page.getByRole('button',{name:/Layouts/}).click();await page.getByRole('button',{name:'Current village The latest garden, bird clearing and friends.',exact:true}).click();state=await snapshot();
  check(state.layout.objects.length===original.objects.length,'Protected village preset preserves every default object');
  check(JSON.stringify(state.layout.objects)===JSON.stringify(presetBefore.layout.objects),'Working copy exactly matches the saved default transforms');
  check(state.layout.objects.filter(o=>o.asset==='white-dove').length===12&&state.layout.objects.some(o=>o.id==='resident-wren')&&state.layout.objects.some(o=>o.asset==='bird-clearing-terrace'),'Updated default includes the dove flock, Wren and bird-clearing scenery');
  await page.screenshot({path:path.join(evidence,'editor-overview.png')});
  await page.getByRole('button',{name:'Select a cottage',exact:true}).click();
  const selectedId=(await page.evaluate(()=>window.cosyStudio.selection()))[0];
  let cottage=state.layout.objects.find(o=>o.id===selectedId);check(cottage.rotation[1]===-90,'Inspector receives the original house rotation');
  await page.locator('[data-tool="translate"]').click();
  await page.waitForTimeout(150); // TransformControls updates its raycast handles on a render frame.
  const pivot=await page.evaluate(id=>window.cosyStudio.screenPoint(id,[0,0,0]),selectedId);
  await page.mouse.move(pivot.x,pivot.y-32);await page.mouse.down();await page.mouse.move(pivot.x,pivot.y-92,{steps:15});await page.mouse.up();
  check((await snapshot()).layout.objects.find(o=>o.id===selectedId).position[1]>0,'Dragging the move handle raises the selected cottage');
  await page.getByRole('button',{name:'Set on ground',exact:false}).click();
  check(Math.abs((await snapshot()).layout.objects.find(o=>o.id===selectedId).position[1])<.1,'Set on ground restores the cottage to the terrain');
  await page.locator('[data-tool="select"]').click();await page.keyboard.press('Escape');
  const center=await page.evaluate(id=>window.cosyStudio.screenPoint(id),selectedId);await page.mouse.click(center.x,center.y);
  check((await page.evaluate(()=>window.cosyStudio.selection()))[0]===selectedId,'Clicking the visible cottage selects its complete asset');
  await page.getByRole('spinbutton',{name:'Rotation Y',exact:true}).fill('30');await page.getByRole('spinbutton',{name:'Rotation Y',exact:true}).press('Tab');
  state=await snapshot();check(state.layout.objects.find(o=>o.id===selectedId).rotation[1]===30,'Numeric rotation edits the house');
  await page.getByRole('button',{name:'Undo',exact:true}).click();check((await snapshot()).layout.objects.find(o=>o.id===selectedId).rotation[1]===-90,'Undo restores the house rotation');
  await page.getByRole('button',{name:'Redo',exact:true}).click();check((await snapshot()).layout.objects.find(o=>o.id===selectedId).rotation[1]===30,'Redo restores the edit');
  await page.getByRole('spinbutton',{name:'Scale X',exact:true}).fill('1.2');await page.getByRole('spinbutton',{name:'Scale X',exact:true}).press('Tab');
  check((await snapshot()).layout.objects.find(o=>o.id===selectedId).scale.every(n=>n===1.2),'Uniform scaling changes all three axes');
  await page.getByRole('button',{name:'Duplicate',exact:true}).click();
  state=await snapshot();check(state.layout.objects.length===original.objects.length+1,'Duplicate creates a separate layout object');
  let copy=(await page.evaluate(()=>window.cosyStudio.selection()))[0];
  const xBefore=(await snapshot()).layout.objects.find(o=>o.id===copy).position[0];
  await page.keyboard.press('ArrowRight');const x=(await snapshot()).layout.objects.find(o=>o.id===copy).position[0];check(x===xBefore+.5,'Keyboard nudge respects the half-metre grid');
  await page.getByLabel('Locked',{exact:true}).check();await page.keyboard.press('ArrowRight');check((await snapshot()).layout.objects.find(o=>o.id===copy).position[0]===x,'Locked objects ignore keyboard transforms');
  await page.getByLabel('Locked',{exact:true}).uncheck();
  await page.getByRole('button',{name:'Remove',exact:true}).click();check((await snapshot()).layout.objects.length===original.objects.length,'Remove deletes only the working copy object');
  await page.getByRole('button',{name:'Undo',exact:true}).click();check((await snapshot()).layout.objects.some(o=>o.id===copy),'Undo restores removed objects');
  await page.getByRole('tab',{name:/Scene/}).click();
  await page.getByRole('searchbox').fill('cottage');
  const rows=page.locator('.scene-select');await rows.nth(0).click();await rows.nth(1).click({modifiers:['Shift']});
  check((await page.evaluate(()=>window.cosyStudio.selection())).length===2,'Shift selection supports multiple objects');
  const selected=await page.evaluate(()=>window.cosyStudio.selection());
  const beforeMulti=(await snapshot()).layout.objects.filter(o=>selected.includes(o.id));
  await page.locator('[data-turn="45"]').click();
  check((await snapshot()).layout.objects.filter(o=>selected.includes(o.id)).every(o=>o.rotation[1]===beforeMulti.find(b=>b.id===o.id).rotation[1]+45),'Multi-object rotation changes each selected object');
  await page.getByRole('searchbox').fill('');await page.getByRole('tab',{name:'Assets',exact:true}).click();
  await page.getByRole('button',{name:'Frame village',exact:true}).click();await page.getByRole('button',{name:'Top down',exact:true}).click();
  const canvas=page.locator('#viewport > canvas');const bounds=await canvas.boundingBox();
  await page.getByRole('button',{name:'Place Stone arch bridge',exact:true}).click();
  await page.mouse.move(bounds.x+bounds.width*.74,bounds.y+bounds.height*.54);await page.mouse.click(bounds.x+bounds.width*.74,bounds.y+bounds.height*.54);
  state=await snapshot();check(state.layout.objects.filter(o=>o.asset==='bridge').length===2,'Asset placement adds another bridge at the clicked ground position');
  await page.getByRole('button',{name:'Draw path',exact:true}).click();
  for(const [x,y] of [[.7,.6],[.75,.7],[.84,.76]])await page.mouse.click(bounds.x+bounds.width*x,bounds.y+bounds.height*y);
  await page.getByRole('button',{name:'Finish path',exact:true}).click();
  state=await snapshot();const customPath=state.layout.objects.find(o=>o.asset==='custom-path');check(customPath?.path.points.length===3,'Three ground clicks create an editable curved path');
  await page.getByRole('spinbutton',{name:'Width (metres)',exact:true}).fill('3.5');await page.getByRole('spinbutton',{name:'Width (metres)',exact:true}).press('Tab');
  check((await snapshot()).layout.objects.find(o=>o.id===customPath.id).path.width===3.5,'Path width is editable');
  await page.getByRole('button',{name:'Extend by 5 m',exact:true}).click();check((await snapshot()).layout.objects.find(o=>o.id===customPath.id).path.points.length===4,'Path control points can be extended');
  await page.getByRole('button',{name:'Remove path point 4',exact:true}).click();
  await page.getByRole('textbox',{name:'Layout name',exact:true}).fill('Studio QA village');await page.getByRole('textbox',{name:'Layout name',exact:true}).press('Tab');
  await page.getByRole('button',{name:'Save layout',exact:false}).click();await page.waitForFunction(()=>window.cosyStudio.snapshot().fileId!==null);
  const saved=await snapshot();const savedResponse=await (await page.request.get(url+'/api/layouts/'+saved.fileId)).json();
  check(JSON.stringify(savedResponse.layout)===JSON.stringify(saved.layout),'Save writes the exact layout to a local file');
  page.on('dialog',d=>d.accept());await page.reload();await page.waitForFunction(()=>!!window.cosyStudio,{timeout:60000});
  check(JSON.stringify((await snapshot()).layout)===JSON.stringify(saved.layout),'Reload recovers the edited layout');
  await page.getByRole('button',{name:'Play preview',exact:true}).click();check(await page.getByRole('button',{name:/Back to editor/}).isVisible(),'Preview has a directly visible exit');
  await page.keyboard.press('Escape');check(await page.getByRole('button',{name:'Play preview',exact:true}).isVisible(),'Escape returns from preview');
  await page.getByRole('button',{name:/Layouts/}).click();
  const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export JSON',exact:true}).click();const download=await downloadPromise;const downloadPath=await download.path();
  check(JSON.stringify(JSON.parse(fs.readFileSync(downloadPath,'utf8')))===JSON.stringify(saved.layout),'Export downloads the complete layout JSON');
  await page.getByRole('button',{name:'Current village The latest garden, bird clearing and friends.',exact:true}).click();
  const reset=await snapshot();check(reset.fileId===null&&JSON.stringify(reset.layout.objects)===JSON.stringify(original.objects),'Original preset opens a fresh independent copy');
  await page.getByRole('button',{name:'Undo',exact:true}).click();check((await snapshot()).layout.name==='Studio QA village','Opening a preset is undoable');
  await page.getByRole('button',{name:/Layouts/}).click();await page.getByRole('button',{name:'Open meadow The valley, ready for a fresh beginning.',exact:true}).click();
  check(!(await snapshot()).layout.objects.some(o=>o.asset.startsWith('cottage-')),'Open meadow is a distinct scenery-only starter');
  await page.getByRole('button',{name:/Layouts/}).click();await page.getByRole('button',{name:'Riverside retreat Four cottages gathered by the river.',exact:true}).click();
  check((await snapshot()).layout.objects.filter(o=>o.asset.startsWith('cottage-')).length===4,'Riverside retreat supplies a distinct cottage layout');
  await page.getByRole('button',{name:/Layouts/}).click();await page.getByRole('button',{name:'Current village The latest garden, bird clearing and friends.',exact:true}).click();
  await page.getByRole('button',{name:'Select a cottage',exact:true}).click();await page.screenshot({path:path.join(evidence,'editor-house-transform.png')});
  const beforeInvalid=JSON.stringify((await snapshot()).layout);
  const malformed={...saved.layout,objects:[{...saved.layout.objects[0],position:[null,0,0]}]};
  await page.locator('#import-file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(malformed))});
  check(JSON.stringify((await snapshot()).layout)===beforeInvalid,'Invalid import leaves the open layout intact');
  const escaped={...saved.layout,name:'<img src=x onerror=alert(1)>'};
  await page.locator('#import-file').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(escaped))});
  await page.waitForFunction(()=>document.querySelector('#layout-name').value==='<img src=x onerror=alert(1)> copy');
  check(await page.getByRole('textbox',{name:'Layout name',exact:true}).inputValue()==='<img src=x onerror=alert(1)> copy','Imported names remain literal text');
  check(await page.locator('img[onerror]').count()===0,'Imported names cannot inject HTML');
  await page.getByRole('button',{name:'Undo',exact:true}).click();
  await page.setViewportSize({width:1024,height:768});await page.waitForTimeout(800);await page.screenshot({path:path.join(evidence,'editor-tablet.png')});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Tablet layout has no horizontal overflow');
  await page.setViewportSize({width:390,height:844});await page.waitForTimeout(800);await page.screenshot({path:path.join(evidence,'editor-phone.png')});
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Phone layout has no horizontal overflow');
  await page.getByRole('button',{name:'Play preview',exact:true}).click();check(await page.getByRole('button',{name:/Back to editor/}).isVisible(),'Phone preview retains its exit');await page.getByRole('button',{name:/Back to editor/}).click();
  const presetAfter=await(await page.request.get(url+'/api/presets/current-village')).json();check(presetBefore.revision===presetAfter.revision,'All editing, imports and presets leave the original file unchanged');
  check(errors.length===0,'No JavaScript or renderer errors');
  const result={browser:browser.version(),url,checks,errors};fs.writeFileSync(path.join(evidence,'browser-checks.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
