// Use isolated --layouts-dir and --playable-file; this never applies to the real village.
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const assert = require('node:assert/strict');
const url = process.env.STUDIO_URL || 'http://127.0.0.1:3048';
(async () => {
  const browser = await chromium.launch({ channel: 'chrome', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
    const errors = []; page.on('pageerror', error => errors.push(String(error)));
    await page.goto(url); await page.waitForFunction(() => window.cosyStudio, null, { timeout: 90000 });
    const snapshot = () => page.evaluate(() => window.cosyStudio.snapshot());
    const before = await snapshot();
    assert(!(await page.locator('#terrain-tool').isVisible()));
    await page.keyboard.press('t'); assert(await page.locator('#terrain-tool').isVisible());
    assert.equal(await page.locator('#terrain-tool').evaluate(node => !!node.closest('#inspector-panel')), false);
    await page.locator('.asset-card').first().click(); assert(!(await page.locator('#terrain-tool').isVisible()));
    await page.keyboard.press('Escape');
    await page.getByRole('button', { name: 'Top down', exact: true }).click();
    await page.keyboard.press('u');
    const contrast = await page.locator('#finish-path').evaluate(node => {
      const style = getComputedStyle(node), rgb = color => color.match(/[\d.]+/g).slice(0, 3).map(Number).map(n => { n /= 255; return n <= .04045 ? n / 12.92 : ((n + .055) / 1.055) ** 2.4; });
      const luminance = c => { const [r,g,b] = rgb(c); return .2126*r + .7152*g + .0722*b; };
      const a=luminance(style.color), b=luminance(style.backgroundColor); return (Math.max(a,b)+.05)/(Math.min(a,b)+.05);
    });
    assert(contrast >= 4.5, `Finish button contrast ${contrast}`);
    const points = await page.evaluate(() => [[25,-20],[25,-35],[40,-40]].map(([x,z]) => window.cosyStudio.screenPoint('terrain', [x, 0, z])));
    for (const point of points) await page.mouse.click(point.x, point.y);
    await page.getByRole('button', { name: 'Finish river', exact: true }).click();
    const river = (await snapshot()).layout.objects.find(item => !before.layout.objects.some(old => old.id === item.id));
    assert.equal(river.asset, 'custom-river'); assert.equal(river.path.points.length, 3);
    await page.locator('#path-width').fill('8'); await page.locator('#path-width').press('Tab');
    const savedRiver = (await snapshot()).layout.objects.find(item => item.id === river.id); assert.equal(savedRiver.path.width, 8);
    await page.locator('#path-continue').click();
    const extension = await page.evaluate(() => window.cosyStudio.screenPoint('terrain', [45,0,-40]));
    await page.mouse.click(extension.x,extension.y); await page.keyboard.press('Enter');
    assert.equal((await snapshot()).layout.objects.find(item => item.id === river.id).path.points.length,4);
    await page.locator('#undo').click();
    const projection = await page.evaluate(async layout => {
      const { projectWorldLayout } = await import('/modules/features/village/worldLayout.js');
      const { setAuthoredWorld, inRiver } = await import('/modules/features/village/environment.js');
      const { VillageMovement } = await import('/modules/features/village/movement.js');
      const authored = projectWorldLayout(layout); setAuthoredWorld(authored); const stream = authored.rivers.at(-1);
      const [x,z] = stream.spine[Math.floor(stream.spine.length / 2)];
      const player = new VillageMovement([], () => {}); const result = { count: authored.rivers.length, wet: inRiver(x,z), blocked: !player.clear(x,z), dry: !inRiver(x+30,z) }; return result;
    }, (await snapshot()).layout);
    assert(projection.wet && projection.blocked && projection.dry);
    const renderResult = await page.evaluate(async layout => {
      const T = await import('/three/build/three.module.js');
      const { buildWorld } = await import('/modules/features/village/world.js');
      const { projectWorldLayout } = await import('/modules/features/village/worldLayout.js');
      const { setAuthoredWorld, landscapeHeight } = await import('/modules/features/village/environment.js');
      const { StudioCollision } = await import('/modules/tools/village-editor/spatial.js');
      const { VillageNavigation } = await import('/modules/features/village/navigation.js');
      const authored = projectWorldLayout(layout), renderer = new T.WebGLRenderer();
      const world = await buildWorld(() => {}, renderer, undefined, authored);
      let mesh; world.group.traverse(object => { if (object.isMesh && object !== world.water && object.material === world.water.material) mesh = object; });
      const positions = mesh.geometry.attributes.position;
      let error = 0; for (let i=0;i<positions.count;i++) error = Math.max(error, Math.abs(positions.getY(i)-landscapeHeight(positions.getX(i),positions.getZ(i))-.07));
      const nav = new VillageNavigation([], authored);
      const [x,z] = authored.rivers.at(-1).spine[16];
      const model = { assets:new Map(), roots:new Map() }, collision = new StudioCollision(model);
      const item = {id:'wall',asset:'wall',position:[80,0,30],rotation:[0,45,0],scale:[1,1,1],visible:true,locked:false};
      const wall = new T.Mesh(new T.BoxGeometry(.1,5,8),new T.MeshBasicMaterial());
      const root = wall.clone(); root.position.fromArray(item.position); root.rotation.y=Math.PI/4; root.updateMatrixWorld(true);
      model.assets.set('wall',{solid:true,template:wall}); model.roots.set('wall',root);
      collision.refresh({objects:[item]});
      const solid = !collision.playerClear(80,30,0), outside = !collision.playerClear(321,0,0);
      const water = !collision.playerClear(x,z,landscapeHeight(x,z));
      renderer.dispose(); renderer.forceContextLoss(); setAuthoredWorld(projectWorldLayout(window.cosyStudio.snapshot().layout));
      return {error,vertices:positions.count,solid,outside,water,navigationWater:!nav.probe.clear(x,z)};
    }, (await snapshot()).layout);
    assert(renderResult.error < .00001 && renderResult.vertices > 128 && renderResult.solid && renderResult.outside && renderResult.water && renderResult.navigationWater);
    console.log('PASS actual playable river mesh/terrain parity, shared navigation water refusal and preview solid/water/perimeter collision');
    console.log(`PASS contextual elevation, curved river draw/width/projection and button contrast ${contrast.toFixed(2)}:1`);
    await page.keyboard.press("f"); await page.screenshot({path:"/tmp/cosy-tools-river.png"});
    const authored = await snapshot();
    await page.getByRole('button', { name: 'Undo', exact: true }).click();
    assert.equal((await snapshot()).layout.objects.find(item => item.id === river.id).path.width, 6);
    await page.getByRole('button', { name: 'Redo', exact: true }).click(); assert.deepEqual((await snapshot()).layout, authored.layout);
    await page.locator('#save').click(); await page.waitForFunction(() => window.cosyStudio.snapshot().fileId);
    const saved = await snapshot(); await page.reload(); await page.waitForFunction(() => window.cosyStudio, null, { timeout: 90000 });
    assert.deepEqual((await snapshot()).layout, saved.layout);
    await page.keyboard.press('b'); await page.screenshot({ path: '/tmp/cosy-tools-contrast-1280.png' }); await page.keyboard.press('Escape');
    for (const size of [{width:1280,height:800},{width:1024,height:700}]) {
      await page.setViewportSize(size); await page.keyboard.press('t'); await page.waitForTimeout(300);
      const bounds = await page.locator('#sculpt-terrain').boundingBox(); assert(bounds.x >= 0 && bounds.x+bounds.width <= size.width);
      await page.screenshot({ path: `/tmp/cosy-tools-elevation-${size.width}.png` }); await page.keyboard.press('Escape');
    }
    await page.keyboard.press("Home");
    const camera = await page.evaluate(() => window.cosyStudio.camera());
    const layoutBeforePlay = (await snapshot()).layout;
    await page.locator('#preview').click();
    assert((await page.evaluate(() => window.cosyStudio.player())).active);
    const start = await page.evaluate(() => window.cosyStudio.player().position);
    await page.keyboard.down('w'); await page.waitForTimeout(650); await page.keyboard.up('w');
    const moved = await page.evaluate(() => window.cosyStudio.player().position);
    assert(Math.hypot(moved[0]-start[0],moved[2]-start[2]) > .4);
    await page.keyboard.press('Space'); await page.waitForTimeout(160);
    assert.equal(await page.evaluate(() => window.cosyStudio.player().grounded), false);
    await page.waitForTimeout(1100); assert(await page.evaluate(() => window.cosyStudio.player().grounded));
    await page.screenshot({ path: '/tmp/cosy-tools-play-1024.png' });
    await page.keyboard.press('Escape'); assert.equal(await page.evaluate(() => window.cosyStudio.player().active), false);
    const restored = await page.evaluate(() => window.cosyStudio.camera());
    for (const key of ['position','target']) for (let i=0;i<3;i++) assert(Math.abs(restored[key][i]-camera[key][i]) < .01);
    assert.deepEqual((await snapshot()).layout, layoutBeforePlay);
    const playable = await (await page.request.get(`${url}/api/playable`)).json();
    const apply = await page.request.post(`${url}/api/apply`, { data: saved.layout, headers: { Origin:url, 'If-Match':playable.revision } });
    assert.equal(apply.status(),200,await apply.text());
    assert.deepEqual(errors,[]);
    console.log('PASS river undo/redo/save/reload/isolated Apply; laptop tools; blob movement/jump/landing/camera restore; untouched play-test layout; no page errors');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode=1; });
